---
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Reload aliases
  ansible.builtin.shell: |
    set -o pipefail
    newaliases
  args:
    executable: /bin/bash
  register: my_output
  changed_when: my_output.rc != 0
