---
- name: Copy mariadb backup script
  ansible.builtin.copy:
    src: backup_mariadb.sh
    dest: /backup/scripts/backup_mariadb.sh
    owner: root
    group: root
    mode: u+rwx

- name: Copy my.cnf
  ansible.builtin.template:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: u+rw

- name: Create MariaDB backup cronjob
  ansible.builtin.cron:
    name: "mariadb backup"
    minute: "15"
    hour: "2,12"
    job: "mk-job mysqlbackup /backup/scripts/backup_mariadb.sh >/dev/null 2>&1"
