---
- name: Install python packages
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: present

- name: Make sure pymysql is present
  ansible.builtin.package:
    name: python3-pymysql
    state: present

- name: Install maria packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
