---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}\
                                -{{ ansible_facts['distribution_major_version'] }}.yml"

- name: Task mariadb installation
  ansible.builtin.import_tasks:
    file: install_Debian.yml
  when:
    - ansible_facts['distribution'] == "Debian"

- name: Start and enable MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Task mariadb security
  ansible.builtin.import_tasks:
    file: security.yml

- name: Task mariadb dbs
  ansible.builtin.import_tasks:
    file: configure_dbs.yml

- name: Task mariadb backup
  ansible.builtin.import_tasks:
    file: backup.yml

- name: MariaDB monitoring
  ansible.builtin.import_tasks:
    file: mariadb_monitoring.yml
