---
- name: Copy mysql montoring plugin
  ansible.builtin.copy:
    src: /opt/omd/versions/default/share/check_mk/agents/plugins/mk_mysql
    dest: /usr/lib/check_mk_agent/plugins/mk_mysql
    mode: u+rwx
    remote_src: true

- name: Copy mysql.cnf
  ansible.builtin.template:
    src: mysql.cfg
    dest: /etc/check_mk/mysql.cfg
    owner: root
    group: root
    mode: u+r
