---
- name: Install python3-docker
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Copy docker montoring plugin
  ansible.builtin.copy:
    src: /tmp/mk_docker.py
    dest: /usr/lib/check_mk_agent/plugins/mk_docker.py
    mode: '0700'