---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"

- name: CheckMK agent
  ansible.builtin.import_tasks:
    file: agent.yml

- name: CheckMK apt plugin
  ansible.builtin.import_tasks:
    file: mk_apt.yml

- name: "CheckMK agent user {{ checkmk_agent_user }}"
  ansible.builtin.import_tasks:
    file: agent_user.yml

- name: "CheckMK local scripts"
  ansible.builtin.import_tasks:
    file: localscripts.yaml
