---
- name: Update configuration file - /opt/mailcow-dockerized/mailcow.conf
  ansible.builtin.template:
    src: mailcow.conf.j2
    dest: /opt/mailcow-dockerized/mailcow.conf
    owner: root
    group: root
    mode: u+rw
