---
- name: Copy check script for dns
  ansible.builtin.copy:
    src: check_dns.sh
    dest: /usr/lib/check_mk_agent/local/3600/check_dns.sh
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx
