---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}\
                                -{{ ansible_facts['distribution_major_version'] }}.yml"

- name: Install postfix packages
  ansible.builtin.package:
    name: "{{ postfix_packages }}"
    state: present

- name: Disable postfix listener for smtp
  ansible.builtin.lineinfile:
    dest: /etc/postfix/master.cf
    regexp: '^smtp.*inet.*smtpd'
    line: '#\1'
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix relayhost
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^relayhost'
    line: "relayhost = 172.22.1.1"
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix inet_interfaces
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^inet_interfaces'
    line: "inet_interfaces = loopback-only"
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix relay_transport
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^relay_transport'
    line: "relay_transport = relay"
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix default_transport
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^default_transport'
    line: "default_transport = smtp"
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix mydomain
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^mydomain'
    line: "mydomain = {{ mydomain }}"
    state: present
    backup: true
  notify:
    - Restart postfix

- name: Set postfix myhostname
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^myhostname'
    line: "myhostname = {{ myhostname }}"
    state: present
    backup: true
  notify:
    - Restart postfix
