---
- name: Copy fail2ban monitoring script
  ansible.builtin.copy:
    src: check_fail2ban.sh
    dest: /usr/lib/check_mk_agent/local/check_fail2ban.sh
    owner: root
    group: root
    mode: u+rwx,g+rx
