---
- name: Copy fail2ban agent plugin
  ansible.builtin.copy:
    src: /tmp/fail2ban.sh
    dest: /usr/lib/check_mk_agent/plugins/fail2ban.sh
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx
