---
- name: Install finger packages
  ansible.builtin.package:
    name: finger
    state: present

- name: Install mail packages
  ansible.builtin.package:
    name: mailutils
    state: present

- name: copy ssh alert script
  ansible.builtin.copy:
    src: ssh-login-mail.sh
    dest: /opt/ssh-login-mail.sh
    mode: '0755'
  diff: yes

- name: Edit profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: '^/opt/ssh-login-mail.sh '
    line: '/opt/ssh-login-mail.sh | mail -s "SSH Login auf $(hostname)" {{ email }}'