---
- name: Create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.name }} user"
    shell: "/bin/bash"
  with_items:
    - "{{ user }}"

- name: Add authorized key
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.public_ssh_key_source) }}"
    exclusive: true
  with_items:
    - "{{ user }}"
