---
- name: Create user
  user:
    name: "{{ item.name }}"
    comment: "{{ item.name }} user"
    shell: "/bin/bash"
  with_items:
    - "{{ user }}"

- name: Add authorized key
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.public_ssh_key_source) }}"
    exclusive: yes
  with_items:
    - "{{ user }}"