---
- name: Add user
  ansible.builtin.import_tasks:
    file: add_user.yaml

- name: Create backup directory if it does not exist
  ansible.builtin.file:
    path: /backup
    state: directory
    mode: u+rwx,g+rwx,o+rwx

- name: Set aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^root:'
    line: "root: {{ system_email_recipient }}"
    state: present
    backup: yes
  notify:
    - Reload aliases
