---
- name: Set ServerTokens
  ansible.builtin.lineinfile:
    dest: /etc/apache2/apache2.conf
    regexp: '^ServerTokens'
    line: "ServerTokens Prod"
    state: present
    backup: yes
  notify:
    - Restart Apache

- name: Disable the ServerSignature Directive
  ansible.builtin.lineinfile:
    dest: /etc/apache2/apache2.conf
    regexp: '^ServerSignature'
    line: "ServerSignature Off"
    state: present
    backup: yes
  notify:
    - Restart Apache
