---
- name: Task nextcloud backup
  ansible.builtin.import_tasks:
    file: backup.yml

- name: Task nextcloud monitoring
  ansible.builtin.import_tasks:
    file: monitoring.yml

- name: Create nextcloud cron
  ansible.builtin.cron:
    name: "nextcloud cron"
    minute: "*/5"
    user: www-data
    job: mk-job nextcloud_cron php -f /var/www/nextcloud/cron.php

- name: Create the check job directory for www-data
  ansible.builtin.file:
    path: /var/lib/check_mk_agent/job/www-data
    state: directory
    owner: www-data
    group: www-data
    mode: u+rwx,g+rx,o+rx
