---
- name: Set apc
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/mods-available/apcu.ini
    regexp: '^apc.enable_cli'
    line: apc.enable_cli={{ apc_enable_cli }}
  register: apc_phpini

- name: Set timezone
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^date.timezone'
    line: date.timezone = {{ timezone }}
  register: timezone_phpini

- name: Set memory_limit
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^memory_limit '
    line: memory_limit = {{ memory_limit }}
  register: memory_limit_phpini

- name: Set upload_max_filesize
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^upload_max_filesize '
    line: upload_max_filesize = {{ upload_max_filesize }}
  register: upload_max_filesize_phpini

- name: Set post_max_size
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^post_max_size '
    line: post_max_size = {{ post_max_size }}
  register: post_max_size_phpini

- name: Set max_execution_time
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^max_execution_time '
    line: max_execution_time = {{ max_execution_time }}
  register: max_execution_time_phpini

- name: Set file_uploads
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^file_uploads '
    line: file_uploads = {{ file_uploads }}
  register: file_uploads_phpini

- name: Set allow_url_fopen
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^allow_url_fopen '
    line: allow_url_fopen = {{ allow_url_fopen }}
  register: allow_url_fopen_phpini

- name: Set display_errors
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^display_errors '
    line: display_errors = {{ display_errors }}
  register: display_errors_phpini

- name: Set output_buffering
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^output_buffering '
    line: output_buffering = {{ output_buffering }}
  register: output_buffering_phpini

- name: Set zend_extension
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^zend_extension '
    line: zend_extension = {{ zend_extension }}
  register: zend_extension_phpini

- name: Configure opcache
  community.general.ini_file:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: u+rw,g+r
  loop: "{{ opcache_configuration }}"
  register: opcache_phpini

- name: Restart apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted
  when: (apc_phpini.changed) or
        (timezone_phpini.changed) or
        (memory_limit_phpini.changed) or
        (upload_max_filesize_phpini.changed) or
        (post_max_size_phpini.changed) or
        (max_execution_time_phpini.changed) or
        (file_uploads_phpini.changed) or
        (allow_url_fopen_phpini.changed) or
        (display_errors_phpini.changed) or
        (output_buffering_phpini.changed) or
        (zend_extension_phpini.changed) or
        (opcache_phpini.changed)